//Teste de requisições REST em cervejarias

@baseUrl = http://localhost:4000

@id = 60b5af866ac22c24a758dc7a

###
GET {{baseUrl}}/cervejarias
Content-Type: application/json

###
GET {{baseUrl}}/cervejarias/{{id}}
Content-Type: application/json

###
POST {{baseUrl}}/cervejarias
Content-Type: application/json

{
    "nome": "Cervejaria teste",
    "descricao": "Cervejaria para teste do BACKEND do projeto",
    "funcionamento": "Seg a Sex - 15:00 às 00:30",
    "acessibilidade": true,
    "foto": {
        "originalName": "Teste imagem.png",
        "path": "img/teste.png",
        "size": 50,
        "mimetype": "image/png"
    },
    "status": true
}

###
DELETE {{baseUrl}}/cervejarias/{{id}}
Content-Type: application/json

###
PUT {{baseUrl}}/cervejarias
Content-Type: application/json

{
    "_id": "60b5af866ac22c24a758dc7a",
    "nome": "Edit funfou",
    "descricao": "Cervejaria para teste do BACKEND do projeto",
    "acessibilidade": true,
    "status": false
}